### ISSUE TITLE
Research if convertible to .NET Core

### ISSUE THREAD

**Issue by haudan** [GroovemanAndCo/MyOhmStudio#12]
I'd like to build this for MacOS, but we're gonna need to convert the project from .Net Framework to .NET Core. We should research whether this is possible. I assume the biggest blocker is WPF.

**Comment by fab672000** [comment]
Unfortunately, it won't work as it heavily relies on wpf and I don't think I'm going to contribute to AvalonUI (at least yet :) ) to port it
We could probably use Qt/C++ but it is just going to be much longer to achieve the same functionality ( I reuse a lot of packages as you can notice in my about dialog ;-) )
did you try with a VM software ? should work fine that way at least?

-Fab






On Monday, October 12, 2020, 02:01:52 p.m. CDT, Daniel Hauser <notifications@github.com> wrote: 







I'd like to build this for MacOS, but we're gonna need to convert the project from .Net Framework to .NET Core. We should research whether this is possible. I assume the biggest blogger might be WPF.

**Comment by fab672000** [comment]
I like your start on the web client approach on the ohm_downloader, maybe we could have a ASP.NET page that we could reuse and have my code available to you?
Not involved  web technologies but we could maybe learn together.
Otherwise if all you need is a downloader, I think can built on osx console version fairly fast

**Comment by fab672000** [comment]
The conversion to .net core is easy though, the UI has to be redeveloped and osx does not have WPF

**Comment by fab672000** [comment]
Also I can build up to .net4.8 with vs2019 for mac. .net core might be better for server side implementations if you plan to use asp.net though ...

**Comment by haudan** [comment]
> Otherwise if all you need is a downloader, I think can built on osx console version fairly fast

I thought about a command line tool as well, but I'd also like other Ohmies to be able to use this tool, hence the web interface (I know some who are on MacOs).

> I like your start on the web client approach on the ohm_downloader, maybe we could have a ASP.NET page that we could reuse and have my code available to you?

Yeah that could work. Im experimenting with whether the mp4/ogg files can be downloaded directly from the browser, instead of on the server. If not, we're gonna need a backend solution and ASP.net is a good fit, especially if can reuse some of your code. I'll let you know.

The little server I set up on Digitalocean is running Ubuntu 20.04 by the way.

**Comment by fab672000** [comment]
Nice!
For the server, the way I started to refactor what was originally just a week-end code, to get it to a more standard MVVM app: the MainViewModel has all it needs to interface  to the GUI and discuss with the model (the Json data structure).

As I achieve more enhancements (can't believe I already did 7 releases lol! 1.3.3 is now detecting updates and capable of auto-updating) ; I'll continue to decouple the lib for you to be able to use it easily,

Because I designed it from scratch to not mix UI with the model and its algorithms, it should be fast to do.

I'd like to take this opportunity to learn ASP.NET,  so it could be cool if you could indeed start an ASP based server infrastructure there as you seem to be more web oriented than I am, then I could supply well working the code logic?

**Comment by fab672000** [comment]
Closing now as I think we understand the need is more for a GUI development that just porting to .net core and Lisoph web app seems to be a better approach for mac users.
